version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: radio123
      POSTGRES_DB: DataSeekerDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  api:
    build:
      context: .
      args:
        BUILD_MODE: Debug
    container_name: dataseeker
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./src:/src
      - "/home/ben/Documents/slsk logs:/logs"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=DataSeekerDb;Username=postgres;Password=radio123"
