# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "/home/ben/Projects/DataSeeker"
      dockerfile: "Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57412"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dataseeker.api:dev"
    ports:
    - "127.0.0.1:57012:57000"
    - "127.0.0.1:57212:57200"
    - "127.0.0.1:57412:57412"
    volumes:
    - "/home/ben/Projects/DataSeeker/DataSeeker.Api:/app:rw"
    - "/home/ben/Projects/DataSeeker:/src:rw"
    - "/home/ben/.nuget/packages:/root/.nuget/packages"
    - "/home/ben/.local/share/JetBrains/RiderRemoteDebugger/2025.1.5/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/ben/JetBrains Rider-2025.1.4/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ben/.cache/JetBrains/Rider2025.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_8_17_15_01_39:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
